### PR TITLE
Update Map filter to use SafeTypeTransformer to get object's member

### PR DESCRIPTION
**Pull request by nytmo**
partially solving issues #275 , #269
fully solving issue #272

### CODE REVIEW

**Comment by nytmo** [comment]
What is the pourpose of this test?

	CollectionAssert.AreEqual(new[] { new { a = 1 }, new { a = 2 }, new { a = 3 }, new { a = 4 } },
		StandardFilters.Map(new[] { new { a = 1 }, new { a = 2 }, new { a = 3 }, new { a = 4 } }, "b"));

It doesn't make sence to return the same collection, when there is no "b" property! The result should be collection of four empty objects or four nulls, but not the same collection.

**Comment by laedit** [comment]
Thanks for this PR, I will take a look at it as soon as I can.

Regarding your question about the test, I have absolutely no idea. Maybe it is the original behavior from liquid, otherwise I must say that I think the same way as you.

**Comment by nytmo** [comment]
OK, I've written unit test cases for every new use case I might have created, but the coverage isn't changing. Strange enough, that it shows no coverage/no hits on lines where I can prove hit by debugging the test... Really strange...

**Comment by laedit** [comment]
Sounds good to me, thanks a lot! 😄 
About the unit test, I thinks it's ok, maybe the use of `?.` disturbs the code coverage utility.
If you are done with the modifications I will merge the PR.

**Comment by nytmo** [comment]
I've finished the modifications around the map filter. You surely can merge this PR.
The next step will be the sort filter, that suffers from kind of similar issues, but I don't have enough time for this right now. Hopefully, I won't forget about it.

**Pull request merged**
