### PR TITLE
Date filter - "now" reserved string should return correct date time even without format string

### PR DESCRIPTION
**Pull request by nytmo**

### CODE REVIEW

**Comment by nytmo** [comment]
Here it is. I may go (shopping) in peace...

**Comment by laedit** [comment]
Thanks a lot!

**Comment by nytmo** [comment]
You're welcome. Looking forward to find these merges on nuget :)

**Comment by laedit** [comment]
The good news is that the nuget publication is done after each merge in master, so the new version has already been published (2.0.251), even if the nuget website should display it only tomorrow after his indexation.

**Pull request merged**
