### PR TITLE
Support Slice

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by tgjones** [comment]
@rdumont what do you think? This seems like a good change to me - it implements something already in Ruby Liquid, and it has tests. If you're happy with it, you could go ahead and merge it.

**Comment by rdumont** [comment]
@tgjones yes, looks simple enough to me. Merging it!

@jogibear9988 thanks for this contribution! For future reference, though, was that merge from upstream really necessary? The PR would've been cleaner without it.

**Comment by tgjones** [comment]
@rdumont Thanks!

**Comment by jogibear9988** [comment]
@rdumont:
 Sorry, I did not correctly make a Branch for each of my change, I fixed the things I needed and didn't flollow the right workflow! Thanks for merging!

Can you also merge #127 and #128?

After that I've a few more patches in my Branch, most important for me is the change that string filters also work on other types.

**Pull request merged**
