### PR TITLE
Updated to make Rendering and FileSystem operations async by default.

### PR DESCRIPTION
**Pull request by mwadams**
This is a WIP PR that is **not really intended to be merged**, but I am creating it for discussion. (Hence it is created as a draft.)

It is a significant breaking change that changes the file system and rendering operations to be async-by-default.

I would like to create some side-by-side benchmarking to understand the perf impact of these changes in various scenarios.

### CODE REVIEW

**Comment by daviburg** [comment]
Having async as an option, great. Forcing everything to async as a breaking change... maybe not great.

**Comment by mwadams** [comment]
I entirely agree!

**Comment by microalps** [comment]
As this seems to have forked to another library and no feedback on how we can make this backwards compatible, can we close this PR?

**Review by OpenSpacesAndPlaces — COMMENTED** [review]
Is there any reason that adding async/await is being held up? Seems like a good upgrade - especially for heavily modularized rendering.

**Comment by daviburg** [comment]
> Is there any reason that adding async/await is being held up? Seems like a good upgrade - especially for heavily modularized rendering.

This is held up because there is no contributor addressing the acknowledge issues with the draft PR. The draft was done in a major breaking way. If a contributor wanted to step up, the change to asynchronous would need to be introduced as a set of parallel async public APIs, so the existing sync public APIs are not altered, and no existing client is broken.

**Comment by microalps** [comment]
This PR is being abandoned for the following reasons:
* This PR would result in breaking changes as is
* There are unresolved merge conflicts
* Author has not responded in more than a year

**Pull request closed without merging**
