### PR TITLE
Adding global.json for AppVeyor

### PR DESCRIPTION
**Pull request by rolandbaer**
Fixes AppVeyor build problems as described in http://help.appveyor.com/discussions/problems/6324-aspnet-core-builds-now-failing

### CODE REVIEW

**Comment by laedit** [comment]
Thanks a lot for this!
Is the two files necessaries?
The thread linked indicate that the `global.json` need only to be in the folder where the `dotnet` command is run and in this case it's the root.

**Comment by rolandbaer** [comment]
I'm not sure. In the response 3 is written "should be there as well", therefore I added them to both places. I can try if it will work with only the one in the root and then update this PR.

**Comment by laedit** [comment]
Yes please 😄

**Comment by laedit** [comment]
Wonderful, thanks a lot!

**Comment by rolandbaer** [comment]
Wow, fast!
You're welcome. Was a pleasure to help.

**Pull request merged**
