### PR TITLE
Fix Param Whitespace Throws Exception

### LINKED ISSUE #496: Param Whitespace Throws Exception
### Dotliquid version
2.2.656

### Expected behavior
``` {% param date_format='ruby' %} ```
Behave the same as without the trailing whitespace

### Actual behavior
Liquid syntax error: Variable ''ruby' ' was not properly terminated
or (DotLiquid 2.0 Syntax)
Liquid error: Object reference not set to an instance of an object.

### PR DESCRIPTION
**Pull request by microalps**
Resolves #496

### CODE REVIEW

**Comment by microalps** [comment]
The solution is a bit hackish because the following is silently ignored:
``` {% param Syntax = 'DotLiquid21' | replace: '21', '10' %} ```
I don't think we want to support filters here. Simple trim will pass entire string with filters to context, which will obviously fail but without any error handling or messaging that filters are not supported. Suggestions?

**Comment by daviburg** [comment]
> The solution is a bit hackish because the following filter is silently ignored: `{% param Syntax = 'DotLiquid21' | replace: '21', '10' %}` I don't think we want to support filters here. Simple trim will pass entire string with filters to context, which will obviously fail but without any error handling or messaging that filters are not supported. Suggestions?

With simple string trim `{% param Syntax = 'DotLiquid21' | replace: '21', '10' %}` will turn into `{% param Syntax = 'DotLiquid21' | replace: '21', '10'%}`, yes?
What error does user get with this unsupported filter?

Are there scenarios where string trim doesn't fix a whitespace issue but the ().Name hack does fix?

**Comment by microalps** [comment]
@daviburg 
> What error does user get with this unsupported filter?

Liquid syntax error: Invalid syntax option: 'DotLiquid21' | r...
> Are there scenarios where string trim doesn't fix a whitespace issue but the ().Name hack does fix?

Not that I know of. Reran the tests, they all passed.

**Comment by daviburg** [comment]
> @daviburg
> 
> > What error does user get with this unsupported filter?
> 
> Liquid syntax error: Invalid syntax option: 'DotLiquid21' | r...
> 
> > Are there scenarios where string trim doesn't fix a whitespace issue but the ().Name hack does fix?
> 
> Not that I know of. Reran the tests, they all passed.

Then string trim seems a pretty clean option.

**Review by daviburg — APPROVED** [review]

**Pull request merged**
