### PR TITLE
Sorting when only some elements contain the sorting criteria

### PR DESCRIPTION
**Pull request by rolandbaer**
On sorting, it could be that a collection to sort has some elements that contain the sorting property but some other elements do not contain this property. This should not prevent the sorting to take place.
This PR changes the behaviour of the sorting to take place it the sorting property is at least available in one element of the collection.

### CODE REVIEW

**Comment by laedit** [comment]
Thanks a lot, I will review it as soon as possible 😄

**Comment by laedit** [comment]
Can you add a test which demonstrate the new ability?
Thanks.

**Comment by rolandbaer** [comment]
@laedit Test is added.

**Comment by laedit** [comment]
Thanks!

**Pull request merged**
