### PR TITLE
allow IFileSystem return Template instance for better performance

### PR DESCRIPTION
**Pull request by 303248153**
Previously I open #167 for this, today I refork dotliquid and do the same change.
This is a break change so it should't accept until next major update.

### CODE REVIEW

**Comment by bradphelan** [comment]
Can you explain why it is a breaking change? Is the external API changed or do templates generate different results. I'm trying to understand if this is the kind of change that will get noticed by a build failure ( easy to handle ) or a runtime failure with potentially different results ( hard to handle )

**Comment by bradphelan** [comment]
ok. So they will get a compile error and then it's an easy fix. Thanks

**Comment by sebastienros** [comment]
The intent is nice, but the suggested change is not very sound. Using an `object` type just to be able to return some potentially expected other type.

I would suggest to add another service instead, like `ITemplateProvider` which would be called before `IFileSystem`, and after the template is built. This would not break anything and be clear about the intent. The default implementation would just return `null`.

**Comment by tgjones** [comment]
@sebastienros - great idea.

@303248153 I'm going to close this PR, but if you'd like to submit one that implements @sebastienros's idea of an `ITemplateProvider`, I think we'd accept that.

**Pull request closed without merging**
