### PR TITLE
Dictionary access change

### PR DESCRIPTION
**Pull request by jogibear9988**

### CODE REVIEW

**Comment by haf** [comment]
Hi @jogibear9988  can we do #128 instead?

**Comment by jogibear9988** [comment]
Why did you close this? it's also not yet implemented!

**Comment by haf** [comment]
@jogibear9988 Because it would seem #128 is identical?

**Comment by jogibear9988** [comment]
No, the changes to Context.cs are missing in the other one

**Comment by haf** [comment]
Ok, could you please rebase it against master then?

**Comment by jogibear9988** [comment]
will do. monday i think

**Comment by haf** [comment]
Closing since there was no answer. Can be re-opened.

**Pull request closed without merging**
